services:
  screenshot:
    image: playwright-screenshot-tests
    ports:
      - "9323:9323"
    volumes:
      - ./utils:/app/regression-tests/utils
      - ./tests:/app/regression-tests/tests
      - ../playwright.regression.config.ts:/app/playwright.regression.config.ts
      - ../snapshots:/app/snapshots
      - ../playwright-report:/app/playwright-report
      - ../api-requests:/app/api-requests
      - ../.env.local:/app/.env.local
      - ../package.json:/app/package.json
      - ../fixtures:/app/fixtures
      - ../.cache:/app/.cache
      - ../pages:/app/pages
      - ../setup:/app/setup
      - ../test-data:/app/test-data
      - ../utils:/app/utils
    environment:
      - CI=${CI}
      - DOCKER_ENV=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    command: npm run playwright:regression
