"""init migration

Revision ID: 0f57303a227b
Revises: 
Create Date: 2026-03-26 16:58:39.957171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f57303a227b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('user', 'organization', 'data_source', name='tagresourcetype'), server_default='organization', nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('deleted_ts', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'resource_id', 'resource_type', 'deleted_ts', name='uq_tags_active'),
    schema='ffc-api-db'
    )
    op.create_index(op.f('ix_ffc-api-db_tags_id'), 'tags', ['id'], unique=True, schema='ffc-api-db')
    op.create_index(op.f('ix_ffc-api-db_tags_name'), 'tags', ['name'], unique=False, schema='ffc-api-db')
    op.create_index(op.f('ix_ffc-api-db_tags_resource_id'), 'tags', ['resource_id'], unique=False, schema='ffc-api-db')
    op.create_index('ix_tags_resource_lookup', 'tags', ['resource_type', 'resource_id'], unique=False, schema='ffc-api-db')
    op.create_index('ix_tags_resource_name_lookup', 'tags', ['resource_type', 'resource_id', 'name'], unique=False, schema='ffc-api-db')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_resource_name_lookup', table_name='tags', schema='ffc-api-db')
    op.drop_index('ix_tags_resource_lookup', table_name='tags', schema='ffc-api-db')
    op.drop_index(op.f('ix_ffc-api-db_tags_resource_id'), table_name='tags', schema='ffc-api-db')
    op.drop_index(op.f('ix_ffc-api-db_tags_name'), table_name='tags', schema='ffc-api-db')
    op.drop_index(op.f('ix_ffc-api-db_tags_id'), table_name='tags', schema='ffc-api-db')
    op.drop_table('tags', schema='ffc-api-db')
    # ### end Alembic commands ###

