ARG BUILDTAG=build
FROM bi_scheduler:${BUILDTAG}

WORKDIR /usr/src/app/

COPY docker_images/bi_scheduler/__init__.py docker_images/bi_scheduler/
COPY docker_images/bi_scheduler/test_bi_scheduler.py docker_images/bi_scheduler/

CMD ["uv", "--project", "docker_images/bi_scheduler", "run", "python", "-m", "unittest", "docker_images.bi_scheduler.test_bi_scheduler"]
