export interface AuthResponse {
  created_at: string;
  digest: string;
  ip: string
  token: string;
  user_email: string;
  user_id: string;
  valid_until: string;
}

export interface UsersResponse {
  users: [
    {
      created_at: number,
      deleted_at: number,
      id: string,
      display_name: string,
      is_active: boolean,
      type_id: number,
      email: string,
      verified: boolean,
      scope_id: string,
      slack_connected: boolean,
      is_password_autogenerated: boolean,
      jira_connected: boolean,
      last_login: number
    }
  ]
}

