services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    restart: always
    command: bash -c "uv run fastapi dev --host 0.0.0.0 --port 8095"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${FFC_API_PORT:-8095}:8095"

  app_test:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: >
      bash -c "
        set -e

        # Run Ruff to check code style
        uv run ruff check .

        # Check formatting with Ruff
        uv run ruff format --check --diff .

        # Run tests with pytest
        uv run pytest
      "
    volumes:
      - .:/app
    env_file:
      - .env

  bash:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash
    stdin_open: true
    tty: true
    env_file:
      - .env

  format:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: >
      bash -c "
        set -e
        # Run Ruff to fix code style
        uv run ruff check . --fix --fix-only --show-fixes

        # Run Ruff to format code
        uv run ruff format .
      "
    env_file:
      - .env

  bandit:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c "uv run bandit -c pyproject.toml -r ."
    env_file:
      - .env
