---
- name: get the container images that need to be rebuilt
  command:
    argv:
      - find
      - "{{ optscale_dir }}"
      - -mindepth
      - 2
      - -maxdepth
      - 3
      - -name
      - Dockerfile
      - -exec
      - sh
      - -c
      - echo $(basename $(dirname $0))
      - {}
      - ;
  register: containers_to_build

# Building the containers one by one instead of just using `./build.sh --use-nerdctl` to display the progress
# when running the playbook. Also in case of failure it will be clear exactly which item failed
- name: build the container images (this will take awhile, be patient :))
  command: "{{ optscale_dir }}/build.sh --use-nerdctl {{ item }} local"
  args:
    chdir: "{{ optscale_dir }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.HOME }}/bin:{{ ansible_env.PATH }}"
  loop: "{{ containers_to_build.stdout_lines }}"
