---
image_gc_high_threshold: 98
image_gc_low_threshold: 95
eviction_hard: "imagefs.available<5%,memory.available<100Mi,nodefs.available<2Gi,nodefs.inodesFree<5%"
configure_dts_domain: true
install_metrics_server: false
metrics_server_url: "https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml"
components_local_path: "/tmp/components.yaml"
custom_args:
  - --cert-dir=/tmp
  - --secure-port=10250
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s
  - --kubelet-insecure-tls