packages:
  - ui
  - server

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build

# 3 days in minutes
# https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 4320

# https://pnpm.io/settings#trustpolicy
trustPolicy: no-downgrade

# https://pnpm.io/settings#blockexoticsubdeps
blockExoticSubdeps: true
