{{- $config := .Values.jaeger -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.service.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: {{ $config.service.type }}
  ports:
    - port: {{ $config.service.frontendInternalPort }}
      targetPort: frontend
      protocol: TCP
      name: {{ $config.service.name }}-frontend
    - port: {{ $config.service.grpcReceiverExternalPort}}
      targetPort: grpc-receiver
      protocol: TCP
      name: {{ $config.service.name }}-grpc-receiver
    - port: {{ $config.service.httpReceiverExternalPort}}
      targetPort: http-receiver
      protocol: TCP
      name: {{ $config.service.name }}-http-receiver
  selector:
    app: {{ $config.name }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $config.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ $config.name }}
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $config.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $config.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ $config.name }}
        image: "jaegertracing/jaeger:2.14.0"
        imagePullPolicy: {{ $config.image.pullPolicy }}
        ports:
        - containerPort: {{ $config.service.frontendInternalPort }}
          name: frontend
        - containerPort: {{ $config.service.grpcReceiverInternalPort }}
          name: grpc-receiver
        - containerPort: {{ $config.service.httpReceiverInternalPort }}
          name: http-receiver
        env:
        - name: SPAN_STORAGE_TYPE
          value: memory
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
