{{- $config := .Values.migration_job -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        {{- range $config.services }}
        {{- $service_config := get $.Values . }}
        - name: {{ $service_config.service.name }}-migrations
          command: ["/bin/sh", "-c"]
          args:
            - >-
                python -m tools.migrate.migrate {{ $service_config.service.name }} save-config
                --host="{{ $.Values.mariadb.service.name }}"
                --username="{{ $.Values.mariadb.credentials.username }}"
                --password="{{ $.Values.mariadb.credentials.password }}"
                --dbname="{{ $service_config.db.name }}"
                && python -m tools.migrate.migrate {{ $service_config.service.name }} apply
          image: "{{ $service_config.image.repository }}:{{ $service_config.image.tag }}"
          imagePullPolicy: {{ $service_config.image.pullPolicy }}
          {{- end }}
      initContainers:
{{- if .Values.elk.enabled }}
{{ include "wait_for_elk" . | indent 6 }}
{{- end }}
{{ include "wait_mariadb" . | indent 6 }}
      restartPolicy: Never
