{{- $config := .Values.rest_api -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.service.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: {{ $config.service.type }}
  ports:
    - port: {{ $config.service.externalPort }}
      targetPort: {{ $config.service.internalPort }}
      protocol: TCP
      name: {{ $config.service.name }}
  selector:
    app: {{ $config.name }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $config.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $config.name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
{{- if .Values.elk.enabled }}
{{ include "wait_for_elk" . | indent 6 }}
{{- end }}
{{ include "wait_for_service" .Values.etcd | indent 6 }}
{{ include "wait_mariadb" . | indent 6 }}
{{ include "wait_for_service" .Values.rabbitmq | indent 6 }}
{{- if .Values.stripe.enabled }}
{{ include "wait_for_service" .Values.subspector | indent 6 }}
{{- end }}
{{- if .Values.tempo.enabled }}
{{ include "wait_for_tempo_service" .Values.tempo | indent 6 }}
{{- end }}
      containers:
      - name: {{ $config.name }}
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        imagePullPolicy: {{ $config.image.pullPolicy }}
        ports:
        - containerPort: {{ $config.service.internalPort }}
        env:
        - name: IMAGE_ID
          value: {{ $config.image.id }}
        - name: HX_ETCD_HOST
          value: {{ .Values.etcd.service.name }}
        - name: HX_ETCD_PORT
          value: {{ .Values.etcd.service.externalPort | quote }}
        - name: REQUESTS_CA_BUNDLE
          value: /etc/ssl/certs/ca-certificates.crt
        - name: FAKE_CAD_ENABLED
          value: {{ .Values.fake_cad_enabled | quote }}
        - name: OTEL_ENABLED
          value: "1"
        - name: OTEL_EXPORTER
          value: otlp
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        - name: OTEL_SQLALCHEMY_ENABLED
          value: "true"
        - name: OTEL_PYTHON_ASYNCIO_FUTURE_TRACE_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://{{ .Values.tempo.service.name }}.default.svc.{{ .Values.clusterDomain }}:{{ .Values.tempo.service.externalGrpcPort }}"
        - name: OTEL_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_SERVICE_NAME
          value: {{ $config.name }}
        - name: OTEL_SERVICE_VERSION
          value: {{ $config.image.tag }}
        - name: OTEL_PYTHON_LOG_CORRELATION
          value: "true"
{{ include "ready_probe" $config | indent 8 }}
