name: 'Check Jira Issues'
description: 'Check for the existence of Jira issues given a JQL string.'
inputs:
  jira_base_url:
    description: 'The base URL of the Jira Cloud instance.'
    required: true
  jira_user_email:
    description: 'Jira username or email address.'
    required: true
  jira_api_token:
    description: 'Jira API token.'
    required: true
  jql:
    description: 'The JQL query to check for issues.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
