ARG BUILDTAG=build
ARG IMAGE=
FROM ${IMAGE}:${BUILDTAG}
ARG PROJECT=
LABEL org.opencontainers.image.authors="Hystax"

ENV PYTHONPATH=/usr/src/app
COPY docker_images/.pylintrc ./
RUN uv --project docker_images/${PROJECT} sync --locked
