---
# TODO: This is a hack, there must be a better solution
- name: change the /optscale/influxdb permissions
  file:
    path: /optscale/influxdb
    state: directory
    mode: '1777'
# TODO: Fix this hack again, without it we get this error: level=error err="mkdir /var/thanos/data/meta-syncer: permission denied
# before that /optscale/thanos-storegateway had 755 permissions with root being the owner. an update in thanos / minio images caused this
- name: change the thanos config permissions
  file:
    path: /optscale/thanos-storegateway
    state: directory
    mode: '1777'


- name: install the system packages to run the deployment  
  apt:
    name:
      - python3-pip
      - sshpass
      - git
      - python3-virtualenv
      - python3
      - python3-venv
      - python3-dev
    state: present
    update_cache: yes
  become: true

- name: install the python dependancies for Optscale-deploy
  pip:
    requirements: "{{ optscale_deploy_dir }}/requirements.txt"
    virtualenv: "{{ optscale_deploy_dir }}/.venv"

- name: change the cluster secret to a new random UUID
  command:
    argv:
      - sed
      - "s/^  cluster:.*$/  cluster: {{ new_cluster_secret }}/"
      - -i
      - "{{ user_template_overlay }}"

- name: run the k8s cluster setup script
  command:
    argv:
      - "{{ optscale_deploy_dir }}/.venv/bin/python"
      - runkube.py
      - --no-pull
      - -o
      - "{{ user_template_overlay }}"
      - --
      - "{{ k8s_deployment_name }}"
      - local
  args:
    chdir: "{{ optscale_deploy_dir }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.HOME }}/bin:{{ ansible_env.PATH }}"

- name: get the Kubernetes cluster IP address
  command:
    argv:
      - kubectl
      - get
      - services
      - --no-headers
      - --field-selector
      - metadata.name=ngingress-nginx-ingress-controller
      - -o
      - custom-columns=ClusterIP:.spec.clusterIP
  register: k8s_cluster_ip_result

- name: print the Kubernetes cluster IP address
  debug:
    msg: "The k8s cluster has been deployed successfully, cluster IP: {{ k8s_cluster_ip_result.stdout }}"
