import { Locator } from '@playwright/test';

export interface LiveDemoAuthResponse {
  organization_id: string;
  email: string;
  password: string;
  created_at: number;
}

export interface DemoAuthCredentials extends LiveDemoAuthResponse {
  baseApiUrl: string;
}

export interface AuthResponse {
  created_at: string;
  digest: string;
  ip: string;
  token: string;
  user_email: string;
  user_id: string;
  valid_until: string;
}

export interface UsersResponse {
  users: [
    {
      created_at: number;
      deleted_at: number;
      id: string;
      display_name: string;
      is_active: boolean;
      type_id: number;
      email: string;
      verified: boolean;
      scope_id: string;
      slack_connected: boolean;
      is_password_autogenerated: boolean;
      jira_connected: boolean;
      last_login: number;
    },
  ];
}

export interface ServiceNameExpenseSummary {
  total: number;
  previous_total: number;
}

export interface ServiceNameExpensesResponse {
  start_date: number;
  end_date: number;
  breakdown_by: 'service_name';
  counts: Record<string, ServiceNameExpenseSummary>;
  breakdown: Record<string, Record<string, { cost: number }>>;
}

export interface ServiceNameResourceSummary {
  total: number;
  average: number;
}

export interface ServiceNameResourceResponse {
  start_date: number;
  end_date: number;
  breakdown_by: 'service_name';
  counts: Record<string, ServiceNameResourceSummary>;
  breakdown: Record<string, unknown>; // Update if you know what it looks like
}

export interface TagsBreakdownItem {
  tag: string | null;
  count: number;
  cost: number;
}

export interface TagsResponse {
  start_date: number;
  end_date: number;
  breakdown: TagsBreakdownItem[];
}

export interface RegionExpenseSummary {
  total: number;
  previous_total: number;
}

export interface RegionBreakdownEntry {
  [regionName: string]: {
    cost: number;
  };
}

export interface RegionExpensesResponse {
  start_date: number;
  end_date: number;
  breakdown_by: 'region';
  previous_range_start: number;
  total: number;
  previous_total: number;
  counts: Record<string, RegionExpenseSummary>;
  breakdown: Record<string, RegionBreakdownEntry>;
}

export interface ResourceTypeBreakdownItem {
  cost: number;
}

export interface ResourceTypeExpensesResponse {
  start_date: number;
  end_date: number;
  previous_range_start: number;
  breakdown_by: string;
  total: number;
  breakdown: {
    [timestamp: string]: {
      [resourceType: string]: ResourceTypeBreakdownItem;
    };
  };
  counts: {
    [resourceType: string]: {
      total: number;
      previous_total: number;
    };
  };
}

export interface DataSourceSummary {
  total: number;
  previous_total: number;
  id: string;
  name: string;
  type: string;
}

export interface DataSourceBreakdownItem {
  cost: number;
  id: string;
  name: string;
  type: string;
}

export interface DataSourceExpensesResponse {
  start_date: number;
  end_date: number;
  previous_range_start: number;
  total: number;
  breakdown_by: 'cloud_account_id'; // ← API term
  counts: Record<string, DataSourceSummary>;
  breakdown: Record<string, Record<string, DataSourceBreakdownItem>>;
}

export interface OwnerSummary {
  total: number;
  previous_total: number;
  id: string;
  name: string;
}

export interface OwnerBreakdownItem {
  cost: number;
  id: string;
  name: string;
}

export interface OwnerExpensesResponse {
  start_date: number;
  end_date: number;
  previous_range_start: number;
  total: number;
  previous_total: number;
  breakdown_by: 'employee_id'; // Matches API field
  counts: Record<string, OwnerSummary>;
  breakdown: Record<string, Record<string, OwnerBreakdownItem>>;
}

export interface PoolSummary {
  total: number;
  previous_total: number;
  id: string;
  name: string;
  purpose: string;
}

export interface PoolBreakdownItem {
  cost: number;
  id: string;
  name: string;
  purpose: string;
}

export interface PoolExpensesResponse {
  start_date: number;
  end_date: number;
  previous_range_start: number;
  total: number;
  breakdown_by: 'pool_id';
  counts: Record<string, PoolSummary>;
  breakdown: Record<string, Record<string, PoolBreakdownItem>>;
}

export interface K8sNodeSummary {
  total: number;
  previous_total: number;
}

export interface K8sNodeBreakdownItem {
  cost: number;
}

export interface K8sNodeExpensesResponse {
  start_date: number;
  end_date: number;
  previous_range_start: number;
  total: number;
  previous_total: number;
  breakdown_by: 'k8s_node';
  counts: Record<string, K8sNodeSummary>;
  breakdown: Record<string, Record<string, K8sNodeBreakdownItem>>;
}

export interface K8sNamespaceSummary {
  total: number;
  previous_total: number;
}

export interface K8sNamespaceBreakdownItem {
  cost: number;
}

export interface K8sNamespaceExpensesResponse {
  start_date: number;
  end_date: number;
  previous_range_start: number;
  total: number;
  previous_total: number;
  breakdown_by: 'k8s_namespace';
  counts: Record<string | null, K8sNamespaceSummary>;
  breakdown: Record<string, Record<string | null, K8sNamespaceBreakdownItem>>;
}

export interface K8sServiceSummary {
  total: number;
  previous_total: number;
}

export interface K8sServiceBreakdownItem {
  cost: number;
}

export interface K8sServiceExpensesResponse {
  start_date: number;
  end_date: number;
  previous_range_start: number;
  total: number;
  previous_total: number;
  breakdown_by: 'k8s_service';
  counts: Record<string, K8sServiceSummary>;
  breakdown: Record<string, Record<string, K8sServiceBreakdownItem>>;
}

export interface DataSourcesResponse {
  data: {
    dataSources: [
      {
        account_id: number;
        created_at: number;
        id: string;
        last_getting_metric_attempt_at: number;
        last_getting_metric_attempt_error: string | null;
        last_getting_metrics_at: number;
        last_import_at: number;
        last_import_attempt_at: number;
        last_import_attempt_error: string | null;
        name: string;
        parent_id: string | null;
        type: string;
        details: {
          cost: number;
          resources: number;
          forecast: number;
          last_month_cost: number;
          __typename: string;
        };
        config: unknown;
        __typename: string;
      },
    ];
  };
}

export interface DataSourceBillingResponse {
  data: {
    dataSource: {
      account_id: string;
      id: string;
      last_getting_metric_attempt_at: number;
      last_getting_metric_attempt_error: string;
      last_getting_metrics_at: number;
      last_import_at: number;
      last_import_attempt_at: number;
      last_import_attempt_error: string;
      name: string;
      parent_id: string;
      type: string;
      details: {
        cost: number;
        discovery_infos: DataSourceDiscoveryInfo[];
        forecast: number;
        last_month_cost: number;
        resources: number;
        __typename: string;
      };
      config: {
        client_id: string;
        expense_import_scheme: string;
        subscription_id: string;
        tenant: string;
        export_name: string | null;
        container: string | null;
        directory: string | null;
        __typename: string;
      };
      __typename: string;
    };
  };
}

export interface DataSourceDiscoveryInfo {
  cloud_account_id: string;
  created_at: number;
  deleted_at: number;
  enabled: boolean;
  id: string;
  last_discovery_at: number;
  last_error: string | null;
  last_error_at: number;
  observe_time: number;
  resource_type: string;
  __typename: string;
}

export interface CloudAccountsResponse {
  cloud_accounts: CloudAccount[];
}

export interface CloudAccount {
  deleted_at: number;
  id: string;
  created_at: number;
  name: string;
  type: string;
  config: {
    client_id: string;
    secret: string;
    tenant: string;
    skipped_subscriptions: any;
    subscription_id: string;
    expense_import_scheme: string;
  };
  organization_id: string;
  auto_import: boolean;
  import_period: number;
  last_import_at: number;
  last_import_modified_at: number;
  account_id: string;
  process_recommendations: boolean;
  last_import_attempt_at: number;
  last_import_attempt_error: string;
  last_getting_metrics_at: number;
  last_getting_metric_attempt_at: number;
  last_getting_metric_attempt_error: string;
  cleaned_at: number;
  parent_id: string;
}

export type CardMetaData = {
  name: string;
  savingsValue?: Locator;
  countValue?: Locator;
  seeAllBtn: Locator;
  errorLocator: Locator;
  tableLocator?: Locator;
  modalColumnLocator?: Locator;
};

export interface ExpensesResponse {
  expenses: {
    total: number;
    previous_total: number;
    previous_range_start: number;
    id: string;
    name: string;
    breakdown: {
      [timestamp: number]: number;
    };
  };
}

export interface ExpensesFilterByDataSourceResponse {
  expenses: {
    total: number;
    previous_total: number;
    previous_range_start: number;
    id: string;
    name: string;
    breakdown: Record<`${number}`, DataSourceExpense[]>;
    cloud: CloudTotals[];
  };
}

export interface DataSourceExpense {
  id: string;
  name: string;
  type: string;
  expense: number;
}

export interface CloudTotals {
  id: string;
  name: string;
  type: string;
  total: number;
  previous_total: number;
}

export interface ExpensesFilterByPoolResponse {
  expenses: {
    total: number;
    previous_total: number;
    previous_range_start: number;
    id: string;
    name: string;
    breakdown: Record<`${number}`, PoolExpense[]>;
  };
}

export interface PoolExpense {
  id: string;
  name: string;
  purpose: string;
  expense: number;
}

export interface ExpensesFilterByEmployeeResponse {
  expenses: {
    total: number;
    previous_total: number;
    previous_range_start: number;
    id: string;
    name: string;
    breakdown: Record<`${number}`, EmployeeExpense[]>;
  };
}

export interface EmployeeExpense {
  id: string;
  name: string;
  expense: number;
}

export interface EmployeesResponse {
  employees: [
    {
      deleted_at: 0;
      id: string;
      created_at: number;
      name: string;
      organization_id: string;
      auth_user_id: string;
      default_ssh_key_id: null;
      slack_connected: false;
      jira_connected: false;
      last_login: number;
      user_display_name: string;
      user_email: string;
      assignments: [];
    },
  ];
}

export interface DefaultAnomalyResponse {
  organization_constraints: [
    {
      deleted_at: number;
      id: string;
      created_at: number;
      name: string;
      organization_id: string;
      type: string;
      definition: {
        threshold_days: number;
        threshold: number;
      };
      filters: Record<string, unknown>;
      last_run: number;
      last_run_result: {
        average: number;
        today: number;
        breakdown: Record<string, number> | null;
      };
      limit_hits: any[];
    },
  ];
}

export interface CreateAnomalyPolicyResponse {
  deleted_at: number;
  id: string;
  created_at: number;
  name: string;
  organization_id: string;
  type: string;
  definition: {
    threshold_days: number;
    threshold: number;
  };
  filters: Record<string, unknown>;
  last_run: number;
  last_run_result: Record<string, unknown>;
}

export interface AnomalyExpensesDailyBreakdownResponse {
  expensesDailyBreakdown: {
    breakdown: {
      [timestamp: number]: {
        [serviceName: string]: {
          cost: number;
        };
      };
    };
  };
}

/**
 * Budget/Quota policies returned by the API
 */
export interface PolicyBudgetAndQuotaResponse {
  organization_constraints: [
    {
      id: string;
      created_at: number;
      deleted_at: number;
      name: string;
      organization_id: string;
      type: 'recurring_budget' | 'resource_quota' | 'expiring_budget';

      definition: PolicyDefinition;

      filters?: Record<string, { name: string }>;

      last_run: number;
      last_run_result: {
        limit: number;
        current: number;
      };

      limit_hits: {
        id: string;
        deleted_at: number;
        created_at: number;
        organization_id: string;
        constraint_id: string;
        constraint_limit: number;
        value: number;

        run_result: {
          limit: number;
          current: number;
        };
      };
    },
  ];
}

export interface TaggingPolicyResponse {
  organization_constraints: [
    {
      deleted_at: number;
      id: string;
      created_at: number;
      name: string;
      organization_id: string;
      type: 'tagging_policy';
      definition: {
        start_date: number;
        conditions:
          | {
              tag: string;
              without_tag: string;
            }
          | { tag: string }
          | { without_tag: string };
      };
      filters?: [Record<string, { name: string }>];
      last_run: number;
      last_run_result: {
        value: number;
      };
      limit_hits: [
        {
          deleted_at: number;
          id: string;
          organization_id: string;
          constraint_id: string;
          constraint_limit: number;
          value: number;
          created_at: number;
          run_result: {
            value: number;
          };
        },
      ];
    },
  ];
}

/**
 * Definition differs by policy `type`
 * - recurring_budget → { monthly_budget: number }
 * - resource_quota  → { max_value: number }
 * - expiring_budget → { total_budget: number, start_date: number }
 */
export type PolicyDefinition = RecurringBudgetDefinition | ResourceQuotaDefinition | ExpiringBudgetDefinition;

export interface RecurringBudgetDefinition {
  monthly_budget: number;
}

export interface ResourceQuotaDefinition {
  max_value: number;
}

export interface ExpiringBudgetDefinition {
  total_budget: number;
  start_date: number; // UNIX timestamp
}

export interface PoolsResponse {
  deleted_at: number;
  id: string;
  created_at: number;
  limit: number;
  name: string;
  organization_id: string;
  parent_id: null;
  purpose: string;
  default_owner_id: string;
  default_owner_name: string;
  unallocated_limit: number;
  cost: number;
  forecast: number;
  saving: number;
  total_recommendations: number;
  children: [
    {
      deleted_at: number;
      id: string;
      created_at: number;
      limit: string;
      name: string;
      organization_id: string;
      parent_id: string;
      purpose: string;
      default_owner_id: string;
      default_owner_name: string;
      unallocated_limit: number;
      policies: [];
      cost: number;
      forecast: number;
    },
  ];
  policies: [];
}
