---
- name: Change mmap limit
  lineinfile:
    path: /etc/sysctl.conf
    line: 'vm.max_map_count=262144'
  become: yes

- name: Disable ipv6
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv6.conf.all.disable_ipv6=1'
  become: yes

- name: Change current fs notify instances
  lineinfile:
    path: /etc/sysctl.conf
    line: 'fs.inotify.max_user_instances=512'
  become: yes

- name: Change current mmap limit
  shell: sysctl -w vm.max_map_count=262144
  become: yes

- name: Update /etc/security/limits.conf
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "* soft nofile 165536"
    - "* hard nofile 165536"
  become: yes

- name: Update /etc/systemd/system.conf
  blockinfile:
    path: /etc/systemd/system.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      [Manager]
      DefaultLimitNOFILE=165536
  become: yes

- name: Reload systemd manager configuration
  command: systemctl daemon-reexec
  become: yes

- name: Disable ipv6
  shell: sysctl -q -w net.ipv6.conf.all.disable_ipv6=1
  become: yes

