[project]
name = "metroculus-client"
version = "0.0.0"
description = "OptScale Metroculus Client"
requires-python = ">=3.12.11,<3.13"
dependencies = [
    "requests==2.32.4",
    "retrying==1.4.1",
]

[build-system]
requires = ["setuptools>=69.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["../.."]
include = ["optscale_client.metroculus_client*"]
namespaces = true
