name: Manage PR "bug" label

on:
  pull_request:
    types: [opened]

permissions:
  contents: read # Recommended for actions/checkout
  pull-requests: write
  issues: write

jobs:
  manage-bug-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Check if branch contains "bug"
        id: check-branch
        uses: actions/github-script@v8
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const containsBug = branchName.toLowerCase().startsWith('bug');
            core.setOutput('contains_bug', containsBug.toString());

      - name: Add "bug" label if branch contains "bug"
        if: steps.check-branch.outputs.contains_bug == 'true'
        uses: ./.github/actions/add_pull_request_label
        with:
          label: bug
