name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Get the version'
      id: get_version
      run: echo  "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"

    - name: 'Login to registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
        username: ${{ vars.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and push images'
      run: ./release.sh ${{ vars.REGISTRY_LOGIN_SERVER }} ${{ steps.get_version.outputs.VERSION }}
