name: Sync Branch and Create PR

on:
  schedule:
    - cron: "0 9 * * 1"  # Every Monday at 09:00 UTC
  workflow_dispatch:  # Manual trigger option

permissions:
  actions: write

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for Existing Jira Ticket
        id: check_jira_ticket
        uses: ./.github/actions/check-jira-issues
        with:
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          jql: "project = MPT AND parentEpic = MPT-3562 AND summary ~ __SYNC_UPSTREAM__ AND status NOT IN (Done, Rejected)"

      - name: Create Jira Ticket
        id: create_jira_ticket
        if: steps.check_jira_ticket.outputs.issue == ''
        uses: ./.github/actions/create-jira-issue
        with:
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          project: "MPT"
          issue_type: "Story"
          summary: "__SYNC_UPSTREAM__ Sync OptScale integration -> main"
          description: "This task involves syncing the upstream branch with the main branch and creating a PR."
          fix_version: "v4"
          component: "Extension FinOps"
          assignee: ${{ secrets.JIRA_ASSIGNEE }}
          epic: "MPT-3562"

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/hystax/optscale.git
          git fetch upstream --tags

      - name: Get latest tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Check if branch exists
        run: |
          if git ls-remote --heads origin sync-${{ steps.latest_tag.outputs.LATEST_TAG }} | grep sync-${{ steps.latest_tag.outputs.LATEST_TAG }}; then
            echo "Branch already exists. Skipping..."
            exit 0
          fi

      - name: Create new branch from latest tag
        run: |
          git checkout -b sync-${{ steps.latest_tag.outputs.LATEST_TAG }} ${{ steps.latest_tag.outputs.LATEST_TAG }}
          git push origin sync-${{ steps.latest_tag.outputs.LATEST_TAG }}

      - name: Check if PR exists
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --head 'sync-${{ steps.latest_tag.outputs.LATEST_TAG }}' \
              --base 'main' \
              --json title \
              --jq 'length')
          if ((prs > 0)); then
              echo "pr_exists=true" >> "$GITHUB_OUTPUT"
              echo "::notice::Pull Request exist."
          fi
          

      - name: Get current date
        id: current_date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
              --repo "$GITHUB_REPOSITORY" \
              --head 'sync-${{ steps.latest_tag.outputs.LATEST_TAG }}' \
              --base 'main' \
              --title '${{ steps.check_jira_ticket.outputs.issue }}${{ steps.create_jira_ticket.outputs.issue }} Sync upstream/${{ steps.latest_tag.outputs.LATEST_TAG }} -> main ${{ steps.current_date.outputs.date }}' \
              --body "This PR syncs the latest changes from upstream."
