name: Vulernability Checks
on:
  push:
    branches: [ "main" ]
  pull_request:    
    branches: [ "main" ]
  schedule:
    - cron: '22 23 * * 3'

jobs:
  bandit:
    permissions:
      contents: read 
      security-events: write
      actions: read 

    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
          pip install bandit bandit-sarif-formatter
  
    - name: Run Bandit scan
      shell: bash
      run: |            
            bandit -f sarif -o results.sarif -r . --exit-zero


    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
          name: results.sarif
          path: results.sarif
          

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: results.sarif

  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on:  'ubuntu-latest'
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: javascript-typescript
          build-mode: none
        - language: python
          build-mode: none
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

