---
- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/helm-install.sh
    mode: 0755

- name: Install Helm
  shell: /tmp/helm-install.sh
  become: yes
